In [1]:
cd ../../src/

/Users/in-divye.singh/Documents/Projects/MIC_predictor/src

In [2]:
import pandas as pd

In [5]:
from utils import *

In [6]:
paac = pd.read_csv("../data/pfeature/paac.csv")
#paac = paac.drop(['ID'], axis=1)
cetd = pd.read_csv("../data/pfeature/CeTD.csv")
#cetd = cetd.drop(['ID'], axis=1)
shannon_entropy = pd.read_csv("../data/pfeature/ha_avp_ic50_shannon_entropy.csv")
#shannon_entropy = shannon_entropy.drop(['ID', 'Sequence'], axis=1)
residue_repeats = pd.read_csv("../data/pfeature/ha_avp_ic50_residue_repeat.csv")
#residue_repeats = residue_repeats.drop(['ID', 'Sequence'], axis=1).reset_index(drop=True)

In [7]:
paac

,ID,PAAC1_A,PAAC1_C,PAAC1_D,PAAC1_E,PAAC1_F,PAAC1_G,PAAC1_H,PAAC1_I,PAAC1_K,...,PAAC1_N,PAAC1_P,PAAC1_Q,PAAC1_R,PAAC1_S,PAAC1_T,PAAC1_V,PAAC1_W,PAAC1_Y,PAAC1_lam1
0,Seq1,1.7542,0.0000,0.8771,0.0000,0.0000,2.6313,0.0000,0.0000,0.0000,...,1.7542,0.8771,1.7542,3.5083,0.0000,0.0000,1.7542,0.0000,0.0000,0.1229
1,Seq2,0.8476,0.0000,0.0000,0.0000,0.0000,0.0000,0.8476,1.6953,0.0000,...,0.0000,0.0000,0.8476,2.5429,0.0000,0.8476,0.0000,0.0000,0.0000,0.1524
2,Seq3,0.0000,0.0000,0.9372,0.0000,0.0000,0.9372,0.0000,0.0000,0.0000,...,0.9372,0.9372,0.9372,0.9372,0.9372,0.0000,0.9372,0.0000,0.0000,0.0628
3,Seq4,0.0000,0.0000,0.8873,0.0000,0.0000,1.7747,0.0000,0.0000,0.0000,...,1.7747,0.8873,0.8873,1.7747,0.0000,0.0000,1.7747,0.0000,0.0000,0.1127
4,Seq5,1.7461,0.0000,0.8730,0.0000,0.0000,2.6191,0.0000,0.8730,0.0000,...,0.8730,0.8730,1.7461,3.4922,0.8730,0.0000,0.8730,0.0000,0.0000,0.1270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,Seq708,1.7620,4.4050,0.0000,0.0000,1.7620,3.5240,0.8810,2.6430,1.7620,...,1.7620,1.7620,0.8810,2.6430,0.0000,0.8810,0.8810,0.8810,0.0000,0.1190
708,Seq709,0.0000,0.9102,0.9102,0.0000,0.9102,0.9102,0.9102,0.9102,0.9102,...,0.9102,1.8203,0.9102,2.7305,0.0000,2.7305,0.0000,1.8203,2.7305,0.0898
709,Seq710,0.9253,0.0000,0.9253,5.5516,0.9253,0.0000,0.9253,1.8505,1.8505,...,2.7758,0.0000,3.7011,0.0000,3.7011,0.9253,0.0000,2.7758,0.9253,0.0747
710,Seq711,2.7678,0.0000,4.6130,0.9226,3.6904,3.6904,1.8452,0.0000,1.8452,...,7.3808,6.4582,0.9226,0.0000,1.8452,0.9226,1.8452,1.8452,0.0000,0.0774
711,Seq712,0.0000,0.0000,1.7860,8.0368,0.0000,0.0000,0.0000,2.6789,0.0000,...,1.7860,0.0000,3.5719,4.4649,1.7860,1.7860,0.0000,1.7860,1.7860,0.1070

In [15]:
df = pd.read_csv("../data/raw/hiv_cdhit_filtered.csv")

In [9]:
avp_ic50 = pd.read_csv("../data/raw/AVP-IC50Pred_train.csv")
ha_avp = pd.read_csv("../data/raw/HA_AVP.csv")

In [31]:
df2 = pd.concat([avp_ic50[['Sequence','MIC']], ha_avp], axis=0).drop_duplicates(['Sequence']).reset_index(drop=True)
df2 = sequence_filtering(df2)

In [32]:
df2['ID'] = ["Seq"+str(i) for i in range(1, len(df2)+1)]

In [33]:
df2 = df2.merge(df, on=["Sequence"], how='right')

In [34]:
df2

,Sequence,MIC_x,ID,MIC_y,pIC50
0,ACWAAGIKQEF,333.000,Seq6,333.000,8.007368
1,ACWGAGIKQEF,333.000,Seq7,333.000,8.007368
2,ACWWAGIKAEF,333.000,Seq8,333.000,8.007368
3,ACWWAGIKQAF,333.000,Seq9,333.000,8.007368
4,ACWWAGIRQEF,333.000,Seq10,333.000,8.007368
...,...,...,...,...,...
148,VWGIKQLQARILAVERYLKDQQLLGIWG,0.020,Seq627,0.020,17.727534
149,MTWMEWDREINNYTSLIHSLIEESQNQQEKNEQELLEL,0.008,Seq651,0.008,18.643824
150,MTWEAWDRAIAEYAARIEALIRAAQEQQEKNEAALREL,0.007,Seq654,0.007,18.777356
151,TTWEEWDREINEYTSRIESLIRESQEQQEKNEQELREL,0.005,Seq661,0.005,19.113828
152,WEEWDKKIEEYTKKIEELIKKSEEQQKN,0.002,Seq674,0.002,20.030119

In [53]:
avp_ic50 = pd.read_csv("../data/raw/AVP-IC50Pred_train.csv")
ha_avp = pd.read_csv("../data/raw/HA_AVP.csv")
hiv_df = pd.read_csv("../data/raw/hiv_cdhit_filtered.csv")

df = pd.concat([avp_ic50[['Sequence','MIC']], ha_avp], axis=0).drop_duplicates(['Sequence']).reset_index(drop=True)
df = sequence_filtering(df)
df['ID'] = ["Seq"+str(i) for i in range(1, len(df)+1)]
df = df.merge(hiv_df, on=["Sequence"], how='right')

paac = pd.read_csv("../data/pfeature/paac.csv")
paac = paac[paac.ID.isin(set(df.ID))]
paac = paac.drop(['ID'], axis=1).reset_index(drop=True)
cetd = pd.read_csv("../data/pfeature/CeTD.csv")
cetd = cetd[cetd.ID.isin(set(df.ID))]
cetd = cetd.drop(['ID'], axis=1).reset_index(drop=True)
shannon_entropy = pd.read_csv("../data/pfeature/ha_avp_ic50_shannon_entropy.csv")
shannon_entropy = shannon_entropy[shannon_entropy.Sequence.isin(set(hiv_df.Sequence))]
shannon_entropy = shannon_entropy.drop(['ID', 'Sequence'], axis=1)
residue_repeats = pd.read_csv("../data/pfeature/ha_avp_ic50_residue_repeat.csv")
residue_repeats = residue_repeats[residue_repeats.Sequence.isin(set(hiv_df.Sequence))]
residue_repeats = residue_repeats.drop(['ID', 'Sequence'], axis=1).reset_index(drop=True)

In [57]:
shannon_entropy

,SER_A,SER_C,SER_D,SER_E,SER_F,SER_G,SER_H,SER_I,SER_K,SER_L,SER_M,SER_N,SER_P,SER_Q,SER_R,SER_S,SER_T,SER_V,SER_W,SER_Y
5,-0.511,-0.314,0.000,-0.314,-0.314,-0.314,0.000,-0.314,-0.314,0.000,0.000,0.000,0.0,-0.314,0.000,0.000,0.000,0.000,-0.314,0.000
6,-0.447,-0.314,0.000,-0.314,-0.314,-0.447,0.000,-0.314,-0.314,0.000,0.000,0.000,0.0,-0.314,0.000,0.000,0.000,0.000,-0.314,0.000
7,-0.511,-0.314,0.000,-0.314,-0.314,-0.314,0.000,-0.314,-0.314,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,-0.447,0.000
8,-0.511,-0.314,0.000,0.000,-0.314,-0.314,0.000,-0.314,-0.314,0.000,0.000,0.000,0.0,-0.314,0.000,0.000,0.000,0.000,-0.447,0.000
9,-0.447,-0.314,0.000,-0.314,-0.314,-0.314,0.000,-0.314,0.000,0.000,0.000,0.000,0.0,-0.314,-0.314,0.000,0.000,0.000,-0.447,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
626,-0.272,0.000,-0.172,-0.172,0.000,-0.345,0.000,-0.345,-0.272,-0.444,0.000,0.000,0.0,-0.401,-0.272,0.000,0.000,-0.272,-0.272,-0.172
650,0.000,0.000,-0.138,-0.473,0.000,0.000,-0.138,-0.289,-0.138,-0.385,-0.224,-0.342,0.0,-0.342,-0.138,-0.289,-0.224,0.000,-0.224,-0.138
653,-0.507,0.000,-0.138,-0.450,0.000,0.000,0.000,-0.289,-0.138,-0.289,-0.138,-0.138,0.0,-0.289,-0.342,0.000,-0.138,0.000,-0.224,-0.138
660,0.000,0.000,-0.138,-0.518,0.000,0.000,0.000,-0.289,-0.138,-0.289,0.000,-0.224,0.0,-0.342,-0.342,-0.289,-0.289,0.000,-0.224,-0.138
673,0.000,0.000,-0.172,-0.516,0.000,0.000,0.000,-0.345,-0.500,-0.172,0.000,-0.172,0.0,-0.272,0.000,-0.172,-0.172,0.000,-0.272,-0.172

In [58]:
df = get_net_contact_energy(df)

NameError: name 'get_net_contact_energy' is not defined